### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, 'v'

### ISSUE THREAD

**Issue by vladradishevsky** [hhj1897/face_parsing#3]
How to fix it

Traceback (most recent call last):
  File "face_parsing_test.py", line 141, in <module>
    main()
  File "face_parsing_test.py", line 50, in main
    face_parser = RTNetPredictor(
  File "/home/ml/radishevskii/face_parsing/ibug/face_parsing/parser.py", line 81, in __init__
    ckpt = torch.load(ckpt, 'cpu')
  File "/home/ml/radishevskii/anaconda3/envs/inga_vlad/lib/python3.8/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/ml/radishevskii/anaconda3/envs/inga_vlad/lib/python3.8/site-packages/torch/serialization.py", line 762, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by yiminglin-ai** [comment]
Hi, you have to download the weights using git-lfs, see the installation guide here: https://git-lfs.github.com/

After installing it, run `git lfs pull` and try again.
